# Generated by Django 4.2.11 on 2024-04-07 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvel',
            name='author',
            field=models.ForeignKey(default='11', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
