# Generated by Django 4.2.11 on 2024-04-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_marvel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvel',
            name='url',
            field=models.URLField(default='hh'),
            preserve_default=False,
        ),
    ]
